### ISSUE TITLE
Report Entry text disappearing

### ISSUE THREAD

**Issue by Farnzy** [crobinson42/therms-public#37] opened 2016-04-27 13:18 UTC
When actively typing in a report entry, the textarea will reset and erase text.

There has also been instances where you type the entry and click save and it does not submit.

**Comment by crobinson42** [comment] 2016-04-27 13:54
@Farnzy What browser and device are you using (Chrome, Firefox, iOS, Android)?

**Comment by Farnzy** [comment] 2016-04-27 13:59
Chrome and it is across the board for devices.

**Comment by crobinson42** [comment] 2016-04-27 13:59
You’ve experienced this on mobile and desktop?

**Comment by Farnzy** [comment] 2016-04-27 14:02
Me just on desktop. Will on both devices.

**Comment by crobinson42** [comment] 2016-04-29 15:48
> The bug arises both during editing and during creating new entries with the same editor box.

**Comment by crobinson42** [comment] 2016-04-29 20:34
> Entry form closes
Socket reportEntry.create for report: 5722cb3907b489cf7c74d358
fdb384bd.production.min.js:11 fetchDataStore..
VM914:3 Socket report.update Report ID: undefined
4VM914:5 Socket reportEntry.update for report: 5722cb3907b489cf7c74d358
VM914:3 Socket report.update Report ID: 5722d70f07b489cf7c74d364
VM914:3 Socket report.update Report ID: 5722d74307b489cf7c74d365


> That just happened when it did it again

> It is continuing to spam the report.update output too

**Comment by crobinson42** [comment] 2016-04-30 16:11
I left 3 windows open all night and watched the logs… nothing closed or reset. 1 location had a report with no location saved and the other 2 locations had a report with HQ location saved.

**Comment by crobinson42** [comment] 2016-04-30 19:45
Users are reporting this happening when no other users are online simultaneously..to the best of their knowledge.

**Comment by crobinson42** [comment] 2016-05-01 15:18
> When adding my notes to each Entry I would right around a 2+ lined report and around the end it would back space out of nowhere, this bug resumes each time approximately a minute into the report each time, and the time frame seems to be constant, it acts like its on a setup where if nothing is happening it'll close the report down like a safe mode, even if your adding words the time frame is constant and closes before u have time to finish, I have how ever noticed if i stretch the entry out bigger to observe all i have typed, the issue would not be there and would work, that is 50/50, that's the only bug that frustrates all users. that is all i can give at this time

**Comment by jackschappell** [comment] 2016-05-03 13:00
In Sandbox, the linked bug of the text editor closing all open editor windows when one is saved still exists. I'm not sure if your fix applied to that bug too or not, but I'm not sure if the original can be easily tested in the Sandbox without more users. It is very difficult to recreate, as it appears to be random to the end-user. This may need to be tested in the live environment to see if it returns.

**Comment by crobinson42** [comment] 2016-05-04 04:34
This bug was caused by a parent component that listens to datastore changes and re-renders it's child components on each ds change would also change state of a component that was 'editing' an entry or adding a new entry. Fix put in place and testing in SBX by @jackschappell

**Comment by jackschappell** [comment] 2016-05-08 19:53
This appears to be fixed now.

**Closed by jackschappell** 2016-05-08 19:53 UTC
Labels: bug, high-priority, Production
