### ISSUE TITLE
Some reports not showing under location reports

### ISSUE THREAD

**Issue by cco20916** [crobinson42/therms-public#27] opened 2016-04-22 00:02 UTC
Some reports are missing under the locations reports but the reports can be found if you "Search" them.

**Comment by crobinson42** [comment] 2016-04-23 00:52
@cco20916 can you give some more details on this? Are all locations missing reports or just a specific location? Also, are the reports missing from the top, bottom, or middle of the initial 10 reports that render when you click the location tab?

**Comment by crobinson42** [comment] 2016-04-27 15:25
"current in progress reports don't show under some locations"

**Comment by jackschappell** [comment] 2016-04-28 15:44
I'm finding the exact opposite with the original poster's issue. Completed reports completed by the user where they are the sole author will not appear in report searches, however anything with additional or different authors will regardless of report status. I'm willing to bet these two issues are one in the same, since one location is showing the reports that are missing from the other.

To recreate my version of the bug, start a report and set it to completed. (You may or may not need to approve it too. I haven't confirmed this yet). Make sure you are the sole author. Do a report search and that report should not display in the list of results.

I'm assuming recreating the original bug would be something to a similar effect.

**Comment by crobinson42** [comment] 2016-04-28 15:51
*Not displaying a report in the Report > Search, that has no report entries is expected behavior. 
https://github.com/crobinson42/therms-public/issues/40

They DO/should show up under Location > Reports regardless of report entries and report status.

**Comment by crobinson42** [comment] 2016-05-02 04:49
There's a push to sbx for #40 that should close this out so long as there's still not a remaining issue. I'm unable to reproduce the original issue. @jackschappell this is assigned to you for action.

**Comment by jackschappell** [comment] 2016-05-03 12:57
It seems that my issue is fixed, but I can't confirm the original one as I'm not able to reproduce it either.

**Comment by jackschappell** [comment] 2016-05-08 20:01
I just noticed the original issue the other day. It seems that any recent reports from the last few days aren't showing in the location's list, but in an actual search they come up just fine, just as the original poster described.

**Comment by crobinson42** [comment] 2016-05-08 20:02
This probably has to do with the sort or orderBy method in the DB fetch.

**Comment by jackschappell** [comment] 2016-05-08 20:03
![recentreportsmissingfromloclist](https://cloud.githubusercontent.com/assets/17881452/15100100/25ec714e-151d-11e6-8548-f7be90bd9d37.PNG)

Here is an example. Notice the current date, and the date of the reports being listed. The latest report, which is completed and approved, should be from May 7th, 2016.

**Comment by crobinson42** [comment] 2016-05-09 06:03
this fix is being pushed to SBX.. it was an updated sort query syntax needed in our API.

**Closed** 2016-05-09 06:44 UTC
Labels: bug
