### ISSUE TITLE
Email System

### ISSUE THREAD

**Issue by billpreston** [crobinson42/therms-public#33] opened 2016-04-26 13:36 UTC
Email system only has "Reply" "Mark as Unread" and "Delete"  There is no "Sent" feature to see any replies or what you sent.  There is also no filing system to store emails in so everything stays in the Inbox.

**Comment by jackschappell** [comment] 2016-04-26 13:39
This is a duplicate of issue #31

**Comment by billpreston** [comment] 2016-04-26 13:41
My bad… I apologize…  I’m not having a very good morning this morning…

**Comment by jackschappell** [comment] 2016-04-26 13:42
No worries, sir! It happens!

**Closed by jackschappell** 2016-04-26 13:42 UTC
Labels: duplicate
